##Imports

In [ ]:
# import the necessary packages
import numpy as np
from dataclasses import dataclass, asdict

##Game Setup

In [ ]:
# Define the game state using a dataclass
@dataclass
class RandomGrid():
    state: 'typing.Any' = None  # The current grid state
    to_move: int = 0            # Which player's turn it is: 0 = MAX, 1 = MIN
    num_players: int = 2        # Number of players

    # Creates a new instance of the game with updated attributes
    def update(self, **updates):
        return self.__class__(**{**asdict(self), **updates})

    # Advances to the next player's turn
    def end_turn(self):
        return self.update(to_move=(self.to_move + 1) % self.num_players)

    # Initializes the game with a random 4x4 grid of integers between 0 and 9
    def random_init(self):
        return self.update(state=np.random.randint(0,10,(8,8)))

    # The game ends when the grid is reduced to a single cell
    def is_terminal(self):
        return len(self.state) == 1

    # Returns the utility of the terminal state
    def get_utility(self):
        return self.state[0,0] if self.is_terminal() else None

    # Returns a dictionary of valid moves for the current player
    def get_moves(self):
        if self.to_move == 0:  # MAX player's turn
            return {
                'L': choose_left,
                'R': choose_right
            }
        else:  # MIN player's turn
            return {
                'T': choose_top,
                'B': choose_bottom
            }

# Applies the selected move and ends the turn
def make_move(game, move):
    return move(game).end_turn()

# MAX player move - reduces the grid to the left half
def choose_left(game):
    s = game.state
    return game.update(state=s[:,:int(s.shape[1]/2)])

# MAX player move - reduces the grid to the right half
def choose_right(game):
    s = game.state
    return game.update(state=s[:,int(s.shape[1]/2):])

# MIN player move - reduces the grid to the top half
def choose_top(game):
    s = game.state
    return game.update(state=s[:int(s.shape[0]/2),:])

# MIN player move - reduces the grid to the bottom half
def choose_bottom(game):
    s = game.state
    return game.update(state=s[int(s.shape[0]/2):,:])

##Minimax

In [ ]:
# Returns the optimal minimax value for the current player
def minimax(game):
    """
    Entry point to minimax search.
    If it's MAX's turn, return the result of max_value.
    If it's MIN's turn, return the result of min_value.
    """
    # TODO: Call the correct function depending on who is to move
    pass

# Evaluates the best possible outcome for the MAX player
def max_value(game):
    """
    Return the highest utility value MAX can guarantee from this state,
    along with the move that leads to it.
    """
    # TODO: Implement the MAX player's logic here
    # Base case: return utility if game is terminal
    # Recursive case: evaluate all possible moves and pick the one with max value
    pass

# Evaluates the best possible outcome for the MIN player
def min_value(game):
    """
    Return the lowest utility value MIN can guarantee from this state,
    along with the move that leads to it.
    """
    # TODO: Implement the MIN player's logic here
    # Base case: return utility if game is terminal
    # Recursive case: evaluate all possible moves and pick the one with min value
    pass

##Run Game

In [ ]:
# Main game loop
def play(game):
    # optimal_score = minimax(game)[0]  # Evaluate optimal score
    while not game.is_terminal():
        to_move = game.to_move
        valid_input = False

        while not valid_input:
            allowable_inputs = [m for m in game.get_moves()]

            print(game.state)
            print(f"Player {'MAX' if to_move == 0 else 'MIN'} to move")
            player_input = input(f"Options: {', '.join(allowable_inputs)}\n")

            if player_input in allowable_inputs:
                valid_input = True
            else:
                print(f"Please input one of the following: {', '.join(allowable_inputs)}")

        # Apply the move and switch to the other player
        game = make_move(game, game.get_moves()[player_input])
        print()

    # End of game
    print(f"The outcome of the game is {game.get_utility()}")
    # print(f"The optimal play is {optimal_score}") # Reveal the optimal score

# Start game with a random grid
game = RandomGrid().random_init()
play(game)

[[5 4 0 3 7 1 0 5]
 [0 3 6 0 0 2 4 0]
 [0 4 2 2 5 4 6 7]
 [4 9 9 1 6 7 3 7]
 [2 8 1 0 8 2 7 0]
 [7 0 3 1 5 1 9 3]
 [3 0 5 4 1 6 4 6]
 [8 6 5 5 8 0 9 7]]
Player MAX to move
Options: L, R
T
Please input one of the following: L, R
[[5 4 0 3 7 1 0 5]
 [0 3 6 0 0 2 4 0]
 [0 4 2 2 5 4 6 7]
 [4 9 9 1 6 7 3 7]
 [2 8 1 0 8 2 7 0]
 [7 0 3 1 5 1 9 3]
 [3 0 5 4 1 6 4 6]
 [8 6 5 5 8 0 9 7]]
Player MAX to move
Options: L, R
B
Please input one of the following: L, R
[[5 4 0 3 7 1 0 5]
 [0 3 6 0 0 2 4 0]
 [0 4 2 2 5 4 6 7]
 [4 9 9 1 6 7 3 7]
 [2 8 1 0 8 2 7 0]
 [7 0 3 1 5 1 9 3]
 [3 0 5 4 1 6 4 6]
 [8 6 5 5 8 0 9 7]]
Player MAX to move
Options: L, R
L

[[5 4 0 3]
 [0 3 6 0]
 [0 4 2 2]
 [4 9 9 1]
 [2 8 1 0]
 [7 0 3 1]
 [3 0 5 4]
 [8 6 5 5]]
Player MIN to move
Options: T, B
T

[[5 4 0 3]
 [0 3 6 0]
 [0 4 2 2]
 [4 9 9 1]]
Player MAX to move
Options: L, R
L

[[5 4]
 [0 3]
 [0 4]
 [4 9]]
Player MIN to move
Options: T, B
T

[[5 4]
 [0 3]]
Player MAX to move
Options: L, R
L

[[5]
 [0]]
Player MIN to move
Opt